collector_name: pg_metrics

metrics:
  - metric_name: pg_database_size
    type: gauge
    help: Total database size
    values: [size]
    query: >
      SELECT SUM(pg_database_size(pg_database.datname)) AS size FROM pg_database;

  - metric_name: pg_replication
    type: gauge
    help: Replication lag behind master in seconds
    values: [lag]
    query: >-
      SELECT CASE WHEN NOT pg_is_in_recovery() THEN 0 ELSE GREATEST (0,
      EXTRACT(EPOCH FROM (now() - pg_last_xact_replay_timestamp()))) END AS lag;

  - metric_name: pg_postmaster
    type: gauge
    help: Time at which postmaster started
    values: [start_time_seconds]
    query: >-
      SELECT EXTRACT(EPOCH FROM pg_postmaster_start_time()) AS start_time_seconds;
