---
driver:
  name: podman
platforms:
  - name: rhel9
    image: molecule-rhel9:latest
    dockerfile: Dockerfile
    command: "/usr/sbin/init"
    pre_build_image: false
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

verifier:
  name: testinfra
