---
- name: postgres_exporter | Check if postgres_exporter is installed
  register: postgres_exporter_installed
  ansible.builtin.stat:
    path: "{{ postgres_exporter_install_dir }}/postgres_exporter"

- name: postgres_exporter | Get installed postgres_exporter version
  register: postgres_exporter_version_output
  when: postgres_exporter_installed.stat.exists
  changed_when: false
  ansible.builtin.command:
    cmd: "{{ postgres_exporter_install_dir }}/postgres_exporter --version"

- name: postgres_exporter | Set installed postgres_exporter version
  when: postgres_exporter_installed.stat.exists and postgres_exporter_version_output is defined
  ansible.builtin.set_fact:
    installed_postgres_exporter_version: "{{ postgres_exporter_version_output.stderr | regex_search('version ([0-9]+\\.[0-9]+\\.[0-9]+)', '\\1') | first }}"

- name: postgres_exporter | Download and unarchive postgres_exporter
  register: download_postgres_exporter_result
  when: not postgres_exporter_installed.stat.exists or postgres_exporter_version != installed_postgres_exporter_version
  notify:
    - Copy postgres_exporter binary to {{ postgres_exporter_install_dir }}
    - Remove postgres_exporter binary from {{ postgres_exporter_tmp_dir }}
  ansible.builtin.unarchive:
    src: "{{ postgres_exporter_url }}"
    dest: "{{ postgres_exporter_tmp_dir }}"
    remote_src: true

- name: postgres_exporter | Copy files
  when: create_db_user_result.user is defined
  notify:
    - Restart postgres_exporter
  block:
    - name: postgres_exporter | Create postgres_exporter configs directory
      ansible.builtin.file:
        path: "{{ postgres_exporter_config_dir }}"
        state: directory
        owner: "{{ postgres_exporter_user }}"
        group: "{{ postgres_exporter_user }}"
        mode: "0755"

    - name: postgres_exporter | Copy template files
      ansible.builtin.template:
        src: "{{ __postgres_exporter_item.src }}"
        dest: "{{ __postgres_exporter_item.dest }}"
        owner: "{{ postgres_exporter_user }}"
        group: "{{ postgres_exporter_user }}"
        mode: "0640"
      loop:
        - { src: "postgres_exporter.env.j2", dest: "{{ postgres_exporter_config_dir }}/postgres_exporter.env" }
        - { src: "postgres_exporter.yml.j2", dest: "{{ postgres_exporter_config_dir }}/postgres_exporter.yml" }
        - { src: "postgres_exporter.service.j2", dest: "{{ postgres_exporter_service_dir }}/postgres_exporter.service" }
      loop_control:
        loop_var: __postgres_exporter_item
