---
- name: system | Open port 9187 on RedHat based systems
  ansible.posix.firewalld:
    port: 9187/tcp
    permanent: true
    state: enabled
    immediate: true
  failed_when: false
  when: ansible_os_family == "RedHat"

- name: system | Open port 9187 on Debian based systems
  community.general.ufw:
    rule: allow
    port: "9187"
    proto: "tcp"
  failed_when: false
  when: ansible_os_family == "Debian"

- name: system | Create user "{{ postgres_exporter_user }}"
  ansible.builtin.user:
    name: "{{ postgres_exporter_user }}"
    shell: /bin/false
    state: present
    system: true
  register: create_postgres_exporter_system_user_result
