---
- name: node_exporter | Check if node_exporter is installed
  register: node_exporter_installed
  ansible.builtin.stat:
    path: "{{ node_exporter_install_dir }}/node_exporter"

- name: node_exporter | Get installed node_exporter version
  register: node_exporter_version_output
  when: node_exporter_installed.stat.exists
  changed_when: false
  ansible.builtin.command:
    cmd: "{{ node_exporter_install_dir }}/node_exporter --version"

- name: node_exporter | Set installed node_exporter version
  when: node_exporter_installed.stat.exists and node_exporter_version_output is defined
  ansible.builtin.set_fact:
    installed_node_exporter_version: "{{ node_exporter_version_output.stdout | regex_search('version ([0-9]+\\.[0-9]+\\.[0-9]+)', '\\1') | first }}"

- name: node_exporter | Download and unarchive node_exporter
  register: download_node_exporter_result
  when: not node_exporter_installed.stat.exists or node_exporter_version != installed_node_exporter_version
  notify:
    - Copy node_exporter binary to {{ node_exporter_install_dir }}
    - Remove node_exporter binary from {{ node_exporter_tmp_dir }}
  ansible.builtin.unarchive:
    src: "{{ node_exporter_url }}"
    dest: "{{ node_exporter_tmp_dir }}"
    remote_src: true

- name: node_exporter | Copy files
  notify: Restart node_exporter
  block:
    - name: node_exporter | Copy node_exporter systemd service file
      ansible.builtin.template:
        src: node_exporter.service.j2
        dest: "{{ node_exporter_service_dir }}/node_exporter.service"
        owner: "{{ node_exporter_user }}"
        group: "{{ node_exporter_user }}"
        mode: "0644"
