---
- name: node_exporter | Check if node_exporter is already downloaded
  ansible.builtin.stat:
    path: /tmp/node_exporter-{{ node_exporter_version }}.linux-{{ node_exporter_proc_arch }}/
  register: node_exporter_dir

- name: node_exporter | Download and unarchive node_exporter
  ansible.builtin.unarchive:
    src: "{{ node_exporter_url }}"
    dest: /tmp/
    remote_src: true
  when: not node_exporter_dir.stat.exists
  register: download_node_exporter_result

- name: node_exporter | Copy node_exporter binary to /usr/local/bin
  ansible.builtin.copy:
    src: /tmp/node_exporter-{{ node_exporter_version }}.linux-{{ node_exporter_proc_arch }}/node_exporter
    dest: /usr/local/bin/node_exporter
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_user }}"
    mode: "0755"
    remote_src: true
  when: download_node_exporter_result is changed
  notify: Restart node_exporter

- name: node_exporter | Copy node_exporter systemd service file
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_user }}"
    mode: "0644"
  when: download_node_exporter_result is changed
  notify: Restart node_exporter

- name: Remove node_exporter binary from /tmp
  ansible.builtin.file:
    path: /tmp/node_exporter-{{ node_exporter_version }}.linux-{{ node_exporter_proc_arch }}
    state: absent
  when: node_exporter_dir.stat.exists and download_node_exporter_result is changed
