---
- name: system | Disable SELinux
  ansible.posix.selinux:
    state: disabled
  when: ansible_os_family == "RedHat"

- name: system | Open port 9100
  ansible.posix.firewalld:
    port: 9100/tcp
    permanent: true
    state: enabled
    immediate: true
  failed_when: false
  when: ansible_os_family == "RedHat"

- name: system | Open port 9100
  community.general.ufw:
    rule: allow
    port: "9100"
    proto: "tcp"
  failed_when: false
  when: ansible_os_family == "Debian"

- name: system | Create user "{{ node_exporter_user }}"
  ansible.builtin.user:
    name: "{{ node_exporter_user }}"
    shell: /bin/false
    state: present
    system: true
  register: create_node_exporter_system_user_result
