---
- name: Include tasks to configure system, database and install sql_exporter
  become: true
  block:
    - name: Include task to configure system
      ansible.builtin.include_tasks:
        file: system.yml

    - name: Include task to configure database
      ansible.builtin.include_tasks:
        file: db.yml

    - name: Include task to install sql_exporter
      ansible.builtin.include_tasks:
        file: sql_exporter.yml
