---
- name: sql_exporter | Check if sql_exporter is already downloaded
  ansible.builtin.stat:
    path: /tmp/sql_exporter-{{ sql_exporter_version }}.linux-{{ sql_exporter_proc_arch }}/
  register: sql_exporter_dir

- name: sql_exporter | Download and unarchive sql_exporter
  ansible.builtin.unarchive:
    src: "{{ sql_exporter_url }}"
    dest: /tmp/
    remote_src: true
  when: not sql_exporter_dir.stat.exists
  register: download_sql_exporter_result

- name: sql_exporter | Copy files
  when: create_db_user_result.user is defined
  notify:
    - Restart sql_exporter
  block:
    - name: sql_exporter | Copy sql_exporter binary to /usr/local/bin
      ansible.builtin.copy:
        src: /tmp/sql_exporter-{{ sql_exporter_version }}.linux-{{ sql_exporter_proc_arch }}/sql_exporter
        dest: /usr/local/bin/sql_exporter
        owner: "{{ sql_exporter_user }}"
        group: "{{ sql_exporter_user }}"
        mode: "0755"
        remote_src: true

    - name: sql_exporter | Create sql_exporter configs directory
      ansible.builtin.file:
        path: /opt/sql_exporter
        state: directory
        owner: "{{ sql_exporter_user }}"
        group: "{{ sql_exporter_user }}"
        mode: "0755"

    - name: sql_exporter | Copy sql_exporter metrics file to /opt/sql_exporter
      ansible.builtin.copy:
        src: pg_metrics.collector.yml
        dest: /opt/sql_exporter/pg_metrics.collector.yml
        owner: "{{ sql_exporter_user }}"
        group: "{{ sql_exporter_user }}"
        mode: "0755"

    - name: sql_exporter | Copy template files
      ansible.builtin.template:
        src: "{{ __sql_exporter_item.src }}"
        dest: "{{ __sql_exporter_item.dest }}"
        owner: "{{ sql_exporter_user }}"
        group: "{{ sql_exporter_user }}"
        mode: "0640"
      loop:
        - { src: "sql_exporter.yml.j2", dest: "/opt/sql_exporter/sql_exporter.yml" }
        - { src: "sql_exporter.service.j2", dest: "/etc/systemd/system/sql_exporter.service" }
      loop_control:
        loop_var: __sql_exporter_item

- name: Remove sql_exporter binary from /tmp
  ansible.builtin.file:
    path: /tmp/sql_exporter-{{ sql_exporter_version }}.linux-{{ sql_exporter_proc_arch }}
    state: absent
  when: not sql_exporter_dir.stat.exists and download_sql_exporter_result is succeeded
