---
- name: system | Disable SELinux
  ansible.posix.selinux:
    state: disabled

- name: system | Open port 9399
  ansible.posix.firewalld:
    port: 9399/tcp
    permanent: true
    state: enabled
    immediate: true
  failed_when: false

- name: system | Create user "{{ sql_exporter_user }}"
  ansible.builtin.user:
    name: "{{ sql_exporter_user }}"
    shell: /bin/false
    state: present
    system: true
  register: create_sql_exporter_system_user_result
