---
- name: Restart sql_exporter
  ansible.builtin.systemd_service:
    name: sql_exporter
    state: restarted
    enabled: true
    daemon_reload: true

- name: Copy sql_exporter binary to {{ sql_exporter_install_dir }}
  ansible.builtin.copy:
    src: "{{ sql_exporter_tmp_dir }}/sql_exporter-{{ sql_exporter_version }}.linux-{{ sql_exporter_proc_arch }}/sql_exporter"
    dest: "{{ sql_exporter_install_dir }}/sql_exporter"
    owner: "{{ sql_exporter_user }}"
    group: "{{ sql_exporter_user }}"
    mode: "0755"
    remote_src: true

- name: Remove sql_exporter binary from temporary directory
  ansible.builtin.file:
    path: "{{ sql_exporter_tmp_dir }}/sql_exporter-{{ sql_exporter_version }}.linux-{{ sql_exporter_proc_arch }}"
    state: absent
