---
- name: Include a role from collection
  hosts: all
  gather_facts: true
  tasks:
    - name: Testing the role
      ansible.builtin.include_role:
        name: postgres_exporter
        tasks_from: main.yml
