name: Ansible CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Ansible Playbooks
    runs-on: wsl-ubuntu
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.1"

      - name: Install the project dependencies
        run: uv sync --all-extras --dev

      - name: Run Ansible Lint
        run: ansible-lint playbooks/*.yml
